class GameConstants {
  static const List<String> modes = [
    'Chill',
    'Cheeky',
    'Savage',
    'Pirate',
    'Corporate',
    'Motivational',
    'Shakespearean',
    'Brainrot',
    'Nature Documentary',
    'Sarcasm',
  ];

  static const Map<String, List<String>> roastTemplates = {
    'Chill': [
      'No rush, {name}, the universe is patient',
      'Whenever you\'re ready {name}, we\'ll be here',
      '{name}, the game will still be here in a minute',
      'All good, {name}, take a breath and go',
      '{name}, no stress - just letting you know',
      'Hey, {name}, gentle reminder it\'s your move',
      '{name}, the cosmos awaits your decision',
      'Time flows differently for you {name}',
      '{name}, we\'re all just vibing here',
      'Deep breaths, {name}, then make your move',
      '{name}, no pressure but... yeah it\'s your turn',
      'The zen garden can wait {name}, your move can\'t',
      '{name}, whenever inspiration strikes',
      'No judgement, {name}, but it\'s been a minute',
      'We believe in you {name}, take your time',
    ],
    'Cheeky': [
      '{name}, did you fall asleep or what?',
      'Oi, {name}, paint\'s drying faster than this',
      '{name}, even the snail lapped you twice',
      'Mate, {name}, this isn\'t chess!',
      '{name}, are we boring you?',
      'Wake up, {name}, it\'s go time!',
      '{name}, your turn called - it wants to happen',
      'Righto, {name}, any day now champion',
      '{name}, I\'ve seen glaciers move faster',
      'Mate, {name}, the kettle\'s boiled three times',
      '{name}, did you get lost on the way to your turn?',
      'Absolute scenes, {name}, just go already!',
      '{name}, we\'re not getting any younger here',
      'Come on, {name}, my phone\'s about to die!',
      '{name}, even the loading screen gave up',
    ],
    'Savage': [
      '{name}, you\'re slower than a sloth on sedatives',
      '{name}, I\'ve seen paint dry with more excitement',
      'Wow, {name}, breaking all the slow-motion records',
      '{name}, even Internet Explorer is judging you',
      '{name}, are you playing or conducting a symphony?',
      '{name}, this is genuinely impressive levels of slow',
      '{name}, you\'re making turtles look like Usain Bolt',
      'Mate, {name}, glaciers are sending you motivation quotes',
      '{name}, I didn\'t know time could actually stand still',
      '{name}, you\'re rewriting the laws of physics here',
      'Incredible, {name}, you\'ve weaponized procrastination',
      '{name}, even your future self is bored waiting',
      '{name}, are you okay? Blink twice if you need help',
      '{name}, this performance is truly breathtaking... in the worst way',
      '{name}, you\'ve achieved new levels of disappointing',
    ],
    'Pirate': [
      'Batten down, {name}, or walk the plank!',
      '{name}, ye be slower than barnacles on a hull!',
      'By Davy Jones, {name}, make yer move!',
      'Yo ho, {name}, the seven seas wait for no landlubber!',
      '{name}, ye be testing me patience like a mutinous dog!',
      'Blast ye, {name}, the rum\'s getting warm!',
      '{name}, even the Kraken moved faster!',
      'Heave to, {name}, or I\'ll keelhaul ye!',
      'Sink me, {name}, what be the holdup?',
      '{name}, ye be slower than a ship in the doldrums!',
      'Blow me down, {name}, the treasure won\'t find itself!',
      '{name}, ye scallywag, the crew grows restless!',
      'Dead men tell no tales {name}, but you\'re slower than them!',
      'Pieces of eight {name}, let\'s be having ye!',
      '{name}, even Blackbeard\'s ghost is bored!',
    ],
    'Corporate': [
      '{name}, we need to optimize this throughput',
      'Let\'s touch base {name}, your KPIs are suffering',
      '{name}, this isn\'t very agile of you',
      '{name}, we need to leverage your decision-making capacity',
      'Per my last message {name}, please proceed',
      '{name}, let\'s take this offline and just GO',
      'Your engagement metrics are concerning {name}',
      '{name}, we need to pivot this energy ASAP',
      'Circle back to the game {name}, paradigm shift needed',
      '{name}, let\'s unpack why you\'re still not moving',
      'This impacts our quarterly objectives {name}',
      '{name}, your deliverable is overdue',
      'Low-hanging fruit here {name}, just take your turn',
      '{name}, we need to drill down on your performance',
      'Reaching out {name}, let\'s align on timelines',
    ],
    'Motivational': [
      '{name}, you\'ve got this! But like... NOW!',
      'Come on, {name}, I believe in you - prove me right!',
      '{name}, champions don\'t hesitate - let\'s GO!',
      'You\'re better than this {name}, show us what you\'ve got!',
      '{name}, this is your moment - seize it!',
      'Dig deep, {name}, you didn\'t come this far to wait!',
      '{name}, greatness is one move away - make it happen!',
      'Push through, {name}, you\'re almost there!',
      '{name}, winners take action - be a winner!',
      'I see potential {name}, now show everyone else!',
      '{name}, no excuses - just excellence!',
      'You\'re stronger than you think {name} - prove it!',
      '{name}, this is where legends are made - your turn!',
      'Commitment, {name}, that\'s what separates good from great!',
      '{name}, the only thing standing between you and victory is... you!',
      '{name}, I\'m in your corner - now get in the game!',
      'Channel that energy {name}, turn it into action!',
      '{name}, doubt kills more dreams than failure - move!',
      'You didn\'t train for this {name}, but you\'re ready anyway!',
      '{name}, small steps lead to big wins - start NOW!',
    ],
    'Shakespearean': [
      'Hark, {name}, the hour grows late upon thy turn!',
      'What ho, {name}, makest thou sport of time itself?',
      '{name}, methinks thou art frozen as a statue!',
      'Fie, {name}, dost thou slumber whilst we await?',
      'Prithee, {name}, hasten thy deliberations!',
      '{name}, thou dost try our patience most grievously!',
      'By my troth {name}, the stars have aged in waiting!',
      'Soft, {name}, what delay keeps thee from action?',
      '{name}, thou art slower than a watched pot!',
      'Marry, {name}, the cock hath crowed thrice already!',
      '{name}, time\'s winged chariot races whilst thou dost dawdle!',
      'Forsooth, {name}, even the sundial mocks thy pace!',
      '{name}, thy hesitation would shame a tortoise!',
      'Anon, {name}, lest we all grow grey as winter!',
      '{name}, what tempest stays thy hand from moving?',
      'Odds bodkins, {name}, make thy play!',
      '{name}, thou makest glaciers seem fleet of foot!',
      'Alas, {name}, procrastination is thy master!',
      '{name}, the fates themselves grow weary!',
      'Good, {name}, let not the sun set upon thy turn!',
    ],
    'Brainrot': [
      'Bombardiro, {name}-olino taking forever to make a move!',
      '{name}, transformed into Slothini Procrastinelli!',
      'Tralala, {name} tralala, moving slower than cappuccino cooling!',
      '{name},-errino Delayerotti stuck in the void!',
      'Brrr brrr, {name} brrr - frozen like a gelato statue!',
      '{name} became Waitamundo Foreverini!',
      'Mamma mia, {name}, slower than spaghetti unsticking!',
      '{name}-accino Snoozerelli caught napping!',
      'Ayo, {name} giving Turtle-ino Delayetti energy!',
      '{name} unlocked Procrastino Bufferelli form!',
      'Fratello, {name} slower than pizza delivery!',
      '{name}-arino Stuckamundo needs a push!',
      'Skibidi, {name} toilet-level frozen!',
      '{name}, channeling Snorlax-ino Hibernelli!',
      '{name},-ellini Laggatori buffering hard!',
      'Molto slow, {name}, molto problema!',
      '{name}, entered Slowmo-rino Dimensionelli!',
      '{name},-accio Waitingworth stuck in molasses!',
      'Brainrot, {name} loading... still loading... still loading!',
      '{name}, giving major Yawnino Foreverelli vibes!',
    ],
    'Nature Documentary': [
      'And here we observe {name}, paralyzed by indecision...',
      '{name} remains motionless, conserving precious energy...',
      'The, {name} appears to have entered a state of torpor...',
      'Fascinating, - {name} displays classic avoidance behavior...',
      '{name}, frozen in time like a prehistoric specimen...',
      'Notice how {name} has become one with the furniture...',
      'The, {name} shows no signs of movement in its natural habitat...',
      '{name} demonstrates remarkable stillness, truly remarkable...',
      'We witness {name} in a rare moment of complete inertia...',
      'The, {name} has adopted a defensive waiting strategy...',
      '{name}, perfectly camouflaged as a statue...',
      'And, {name} continues its glacial pace through the terrain...',
      'The, {name} appears to be conducting some sort of meditation...',
      '{name} exhibits behavior typically seen in hibernating species...',
      'Watch as {name} defies the very concept of urgency...',
      'The, {name} has achieved a zen-like state of non-movement...',
      '{name}, demonstrating the patience of a sloth on vacation...',
      'Extraordinary - {name} has broken the record for inactivity...',
      '{name} appears to be studying the game from a distance...',
      'And the {name} remains perfectly still, confusing all observers...',
    ],
    'Sarcasm': [
      'Oh, {name}, take all the time in the world, really',
      'No rush, {name}, it\'s not like anyone else wants to play',
      '{name}, we\'re absolutely thrilled by this wait',
      'Fantastic, {name}, another minute of suspense',
      '{name}, your commitment to slowness is truly inspiring',
      'Brilliant, {name}, really milking this moment',
      '{name}, this is exactly how I wanted to spend my evening',
      'Oh wonderful, {name}, the anticipation is killing us',
      '{name}, please, take another minute to think',
      'Lovely, {name}, we were hoping this would take longer',
      '{name}, your strategic delay is pure genius',
      'Spectacular, {name}, really building that tension',
      '{name}, this waiting game is absolutely riveting',
      'Marvelous, {name}, you\'ve perfected the art of stalling',
      '{name}, clearly you\'re giving this the attention it deserves',
      'Outstanding, {name}, your timing is simply impeccable',
      '{name}, what would we do without these precious moments?',
      'Delightful, {name}, really savoring this aren\'t you?',
      '{name}, your glacial pace is quite the performance',
      'Charming, {name}, we\'re all on the edge of our seats',
    ],
  };

  static const int defaultTimerSeconds = 10;
  static const int minTimerSeconds = 5;
  static const int maxTimerSeconds = 30;
}